name: DBMS workflow

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      id: build_step
      run: mvn clean install
    
    - uses: RubbaBoy/BYOB@v1.1.0
      if: success()
      with:
        name: build_status
        lavel: build
        status: Success
        color: 229954
        github_token: secrets.GITHUB_TOKEN
    
    - uses: RubbaBoy/BYOB@v1.1.0
      if: cancelled() || failure()
      with:
        name: build_status
        lavel: build
        status: Failed
        color: FF0000
        github_token: secrets.GITHUB_TOKEN
    
